export function renderSetupPage(): string {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>连接微信</title><style>
  :root{color-scheme:light;font-family:system-ui,sans-serif}body{margin:0;background:#f3f5f4;color:#17211b;display:grid;place-items:center;min-height:100vh}.card{width:min(420px,calc(100% - 48px));background:white;border-radius:20px;padding:32px;box-shadow:0 16px 50px #17352018;text-align:center}img{width:280px;height:280px;max-width:100%}h1{margin:0 0 8px;font-size:24px}p{color:#617067}.row{display:flex;gap:8px}input{flex:1;padding:11px;border:1px solid #ccd5cf;border-radius:9px}button{border:0;border-radius:9px;padding:11px 16px;background:#07c160;color:white;font-weight:650}button.secondary{background:#e9eeeb;color:#34423a}.hidden{display:none}.error{color:#b42318}</style></head><body><main class="card"><h1>连接微信</h1><p id="status">请用小号微信扫描二维码</p><img id="qr" alt="微信登录二维码"><div id="verify" class="hidden"><p>输入手机微信显示的数字</p><div class="row"><input id="code" inputmode="numeric" maxlength="12"><button id="submit">确认</button></div></div><p id="error" class="error"></p><button id="cancel" class="secondary">取消</button></main><script>
  const base=location.pathname.replace(/\/$/,''); const qr=document.querySelector('#qr'); let qv=-1,done=false;
  async function post(path,body={}){return fetch(base+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});}
  document.querySelector('#submit').onclick=()=>post('/verify',{code:document.querySelector('#code').value});
  document.querySelector('#cancel').onclick=()=>post('/cancel');
  async function tick(){if(done)return;try{const r=await fetch(base+'/status',{cache:'no-store'}),s=await r.json();document.querySelector('#status').textContent=s.message||s.status;document.querySelector('#verify').classList.toggle('hidden',s.status!=='need_verifycode');if(s.qrVersion!==qv){qv=s.qrVersion;qr.src=base+'/qr.png?v='+qv}if(s.status==='connected'){done=true;qr.classList.add('hidden');document.querySelector('#cancel').classList.add('hidden')}if(s.status==='failed'||s.status==='cancelled'){done=true;document.querySelector('#error').textContent=s.message}}catch(e){document.querySelector('#error').textContent='无法读取登录状态';}if(!done)setTimeout(tick,1000)}tick();
</script></body></html>`;
}
